apiVersion: v1
kind: Pod
metadata:
  name: minecraft-server
spec:
  containers:
    - name: minecraft-server
      image: minecraft-server:latest
      ports:
      - containerPort: 25521
      - hostPort: 25521
      env:
      - name: BOT_HOST
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
      - name: BOT_PORT
        value: "80"
      volumeMounts:
      - name: minecraft-data
        mountPath: /data
    
    - name: bot
        image: bot:latest
        env:
        - name: BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: bot-secret
              key: BOT_TOKEN
        - name: CHAT_ID
          valueFrom:
            secretKeyRef:
              name: bot-secret
              key: CHAT_ID
        - name: MESSAGE_ID
          valueFrom:
            secretKeyRef:
              name: bot-secret
              key: MESSAGE_ID
        - name: ADMIN_IDS
          valueFrom:
            secretKeyRef:
              name: bot-secret
              key: ADMIN_IDS
        - name: BOT_PORT
          valueFrom:
            secretKeyRef:
              name: bot-secret
              key: BOT_PORT