// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: api/agent/v1/agent.proto

package agentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Command represents the type of command sent from the bot to the controller
type Command int32

const (
	Command_UNKNOWN        Command = 0
	Command_START_SERVER   Command = 1
	Command_STOP_SERVER    Command = 2
	Command_RESTART_SERVER Command = 3
)

// Enum value maps for Command.
var (
	Command_name = map[int32]string{
		0: "UNKNOWN",
		1: "START_SERVER",
		2: "STOP_SERVER",
		3: "RESTART_SERVER",
	}
	Command_value = map[string]int32{
		"UNKNOWN":        0,
		"START_SERVER":   1,
		"STOP_SERVER":    2,
		"RESTART_SERVER": 3,
	}
)

func (x Command) Enum() *Command {
	p := new(Command)
	*p = x
	return p
}

func (x Command) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Command) Descriptor() protoreflect.EnumDescriptor {
	return file_api_agent_v1_agent_proto_enumTypes[0].Descriptor()
}

func (Command) Type() protoreflect.EnumType {
	return &file_api_agent_v1_agent_proto_enumTypes[0]
}

func (x Command) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Command.Descriptor instead.
func (Command) EnumDescriptor() ([]byte, []int) {
	return file_api_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

type ServerStatus int32

const (
	ServerStatus_NONE     ServerStatus = 0
	ServerStatus_START    ServerStatus = 1
	ServerStatus_RUNNING  ServerStatus = 2
	ServerStatus_STOPPING ServerStatus = 3
)

// Enum value maps for ServerStatus.
var (
	ServerStatus_name = map[int32]string{
		0: "NONE",
		1: "START",
		2: "RUNNING",
		3: "STOPPING",
	}
	ServerStatus_value = map[string]int32{
		"NONE":     0,
		"START":    1,
		"RUNNING":  2,
		"STOPPING": 3,
	}
)

func (x ServerStatus) Enum() *ServerStatus {
	p := new(ServerStatus)
	*p = x
	return p
}

func (x ServerStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServerStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_agent_v1_agent_proto_enumTypes[1].Descriptor()
}

func (ServerStatus) Type() protoreflect.EnumType {
	return &file_api_agent_v1_agent_proto_enumTypes[1]
}

func (x ServerStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServerStatus.Descriptor instead.
func (ServerStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

// Message from bot to controller
type BotMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       Command                `protobuf:"varint,1,opt,name=command,proto3,enum=agent.v1.Command" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BotMessage) Reset() {
	*x = BotMessage{}
	mi := &file_api_agent_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BotMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotMessage) ProtoMessage() {}

func (x *BotMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotMessage.ProtoReflect.Descriptor instead.
func (*BotMessage) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *BotMessage) GetCommand() Command {
	if x != nil {
		return x.Command
	}
	return Command_UNKNOWN
}

// Message from controller to bot
type CtlMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ServerStatus           `protobuf:"varint,1,opt,name=status,proto3,enum=agent.v1.ServerStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CtlMessage) Reset() {
	*x = CtlMessage{}
	mi := &file_api_agent_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CtlMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CtlMessage) ProtoMessage() {}

func (x *CtlMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CtlMessage.ProtoReflect.Descriptor instead.
func (*CtlMessage) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *CtlMessage) GetStatus() ServerStatus {
	if x != nil {
		return x.Status
	}
	return ServerStatus_NONE
}

var File_api_agent_v1_agent_proto protoreflect.FileDescriptor

const file_api_agent_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x18api/agent/v1/agent.proto\x12\bagent.v1\"9\n" +
	"\n" +
	"BotMessage\x12+\n" +
	"\acommand\x18\x01 \x01(\x0e2\x11.agent.v1.CommandR\acommand\"<\n" +
	"\n" +
	"CtlMessage\x12.\n" +
	"\x06status\x18\x01 \x01(\x0e2\x16.agent.v1.ServerStatusR\x06status*M\n" +
	"\aCommand\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x10\n" +
	"\fSTART_SERVER\x10\x01\x12\x0f\n" +
	"\vSTOP_SERVER\x10\x02\x12\x12\n" +
	"\x0eRESTART_SERVER\x10\x03*>\n" +
	"\fServerStatus\x12\b\n" +
	"\x04NONE\x10\x00\x12\t\n" +
	"\x05START\x10\x01\x12\v\n" +
	"\aRUNNING\x10\x02\x12\f\n" +
	"\bSTOPPING\x10\x032I\n" +
	"\fAgentService\x129\n" +
	"\aConnect\x12\x14.agent.v1.CtlMessage\x1a\x14.agent.v1.BotMessage(\x010\x01BDZBgithub.com/Say-2k/minecraft-server-watcher/v2/api/agent/v1;agentpbb\x06proto3"

var (
	file_api_agent_v1_agent_proto_rawDescOnce sync.Once
	file_api_agent_v1_agent_proto_rawDescData []byte
)

func file_api_agent_v1_agent_proto_rawDescGZIP() []byte {
	file_api_agent_v1_agent_proto_rawDescOnce.Do(func() {
		file_api_agent_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_agent_v1_agent_proto_rawDesc), len(file_api_agent_v1_agent_proto_rawDesc)))
	})
	return file_api_agent_v1_agent_proto_rawDescData
}

var file_api_agent_v1_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_agent_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_agent_v1_agent_proto_goTypes = []any{
	(Command)(0),       // 0: agent.v1.Command
	(ServerStatus)(0),  // 1: agent.v1.ServerStatus
	(*BotMessage)(nil), // 2: agent.v1.BotMessage
	(*CtlMessage)(nil), // 3: agent.v1.CtlMessage
}
var file_api_agent_v1_agent_proto_depIdxs = []int32{
	0, // 0: agent.v1.BotMessage.command:type_name -> agent.v1.Command
	1, // 1: agent.v1.CtlMessage.status:type_name -> agent.v1.ServerStatus
	3, // 2: agent.v1.AgentService.Connect:input_type -> agent.v1.CtlMessage
	2, // 3: agent.v1.AgentService.Connect:output_type -> agent.v1.BotMessage
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_agent_v1_agent_proto_init() }
func file_api_agent_v1_agent_proto_init() {
	if File_api_agent_v1_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_agent_v1_agent_proto_rawDesc), len(file_api_agent_v1_agent_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_agent_v1_agent_proto_goTypes,
		DependencyIndexes: file_api_agent_v1_agent_proto_depIdxs,
		EnumInfos:         file_api_agent_v1_agent_proto_enumTypes,
		MessageInfos:      file_api_agent_v1_agent_proto_msgTypes,
	}.Build()
	File_api_agent_v1_agent_proto = out.File
	file_api_agent_v1_agent_proto_goTypes = nil
	file_api_agent_v1_agent_proto_depIdxs = nil
}
